name: Bug Report
description: Found an issue? Tell me about it!
title: "[Bug]: "
labels: ['bug']
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      placeholder: "Provide a more detailed description of the bug, including any observed behaviors, errors, or issues."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: "Describe what you expected to happen when encountering this bug."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce (Optional)
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
