name: Feature Request
description: Suggest a new feature or improvement for the project.
title: "[Feature]: "
labels: ['enhancement']
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      placeholder: "Provide a detailed description of the feature, its benefits, and how it should work."
    validations:
      required: true
