name: Daily Run

on:
  schedule:
    # Runs every day at 6am
    - cron: '0 6 * * *'
  # Allows manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: daily-run
  cancel-in-progress: true

jobs:
  # Using a PAT with repo push access due to branch protection rules which are not supported with
  # the automatic token provided by GitHub Actions at this time
  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
  validate_pat:
    name: "Validate PAT"
    runs-on: ubuntu-latest
    steps:
      - name: Check if PAT is set
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is not set!"
            exit 1
          fi

  build:
    name: "Daily Run"
    runs-on: ubuntu-latest
    needs: validate_pat
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate Feed
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm start

      - name: Configure Git
        run: |
          git config user.name "MHN Events Workflow"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit
        run: git add . && git commit -m "Update feed $(date +'%Y-%m-%d')"

      - name: Publish
        run: git push origin main && git push origin main --tags
