name: Daily Run

on:
  schedule:
    # Runs every day at 6am
    - cron: '0 6 * * *'
  # Allows manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: daily-run
  cancel-in-progress: true

jobs:
  check_secret:
    runs-on: ubuntu-latest
    outputs:
      has_gh_pat: ${{ steps.check.outputs.has_gh_pat }}
    steps:
      - name: Check if PAT is set
        id: check
        run: |
          if [ -n "${{ secrets.GH_PAT }}" ]; then
            echo "::set-output name=has_gh_pat::true"
          else
            echo "::set-output name=has_gh_pat::false"
          fi

  build:
    name: "Daily Run"
    runs-on: ubuntu-latest
    if: needs.check_secret.outputs.has_gh_pat == 'true'
    needs: check_secret
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Publish Feed
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WORKFLOW_GIT_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com
          WORKFLOW_GIT_NAME: "MHN Events Workflow"
        run: npm run publish
