name: Daily Run

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: daily-run
  cancel-in-progress: true

jobs:
  validate_pat:
    name: "Validate PAT"
    runs-on: ubuntu-latest
    steps:
      - name: Check if PAT is set
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is not set!"
            exit 1
          fi

  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    needs: validate_pat
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

  fetch_articles:
    name: "Fetch Articles"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Fetch All Articles
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run fetch:all-articles

  generate_events_json:
    name: "Generate Events JSON"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate Events JSON
        run: npm run generate:events-json

  generate_events_ics:
    name: "Generate Events ICS"
    runs-on: ubuntu-latest
    needs: generate_events_json
    steps:
      - name: Generate Events ICS
        run: npm run generate:events-ics

  configure_git_and_commit:
    name: "Configure Git and Commit"
    runs-on: ubuntu-latest
    needs: [fetch_articles, generate_events_json, generate_events_ics]
    steps:
      - name: Configure Git
        run: |
          git config user.name "MHN Events Workflow"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit
        run: git add . && git commit -m "Update feed $(date +'%Y-%m-%d')"

      - name: Publish
        run: git push origin main && git push origin main --tags
