name: Fetch All Articles

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: fetch-all-articles
  cancel-in-progress: true

jobs:
  build:
    name: "Fetch All Articles"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Start Script
        run: npm run fetch:all-articles
