name: Fetch Article

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Article URL'
        required: true

permissions:
  contents: read

concurrency:
  group: fetch-article-${{ github.event.inputs.url }}
  cancel-in-progress: true

jobs:
  build:
    name: "Fetch Article"
    runs-on: ubuntu-latest

    steps:
      - uses: ./_setup-and-cache.yml

      - name: Run Start Script
        run: npm run fetch:article -- -u ${{ github.event.inputs.url }}
