name: Fetch Article

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Article URL'
        required: true

permissions:
  contents: read

concurrency:
  group: fetch-article-${{ github.event.inputs.url }}
  cancel-in-progress: true

jobs:
  build:
    name: "Fetch Article"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Start Script
        run: npm run fetch:article -- -u ${{ github.event.inputs.url }}
