name: Fetch All Articles

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: fetch-all-articles
  cancel-in-progress: true

jobs:
  build:
    name: "Fetch All Articles"
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/_setup-and-cache.yml
        with:
          runner-type: ubuntu-latest
          CACHE_KEY: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Start Script
        run: npm run fetch:all-articles
